version: 2
updates:
  - package-ecosystem: "npm"
    directory: "apps/web"
    target-branch: "main"
    reviewers:
      - sasicodes
    rebase-strategy: auto
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "apps/embed"
    target-branch: "main"
    reviewers:
      - sasicodes
    rebase-strategy: auto
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "apps/badge"
    target-branch: "main"
    reviewers:
      - sasicodes
    rebase-strategy: auto
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/lens"
    target-branch: "main"
    reviewers:
      - sasicodes
    rebase-strategy: auto
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/eslint-config-weblint"
    target-branch: "main"
    reviewers:
      - sasicodes
    rebase-strategy: auto
    schedule:
      interval: "daily"
  
  - package-ecosystem: "npm"
    directory: "packages/tsconfig"
    target-branch: "main"
    reviewers:
      - sasicodes
    rebase-strategy: auto
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/utils"
    target-branch: "main"
    reviewers:
      - sasicodes
    rebase-strategy: auto
    schedule:
      interval: "daily"
