name = "tower"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true
node_compat = true

routes = [
	{ pattern = "tower.dragverse.app", custom_domain = true }
]

[env.production.vars]
INGEST_REST_ENDPOINT = ""
IP_API_KEY = ""
