name: APPS - Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID_WEB: ${{ secrets.VERCEL_PROJECT_ID_WEB }}
  VERCEL_PROJECT_ID_EMBED: ${{ secrets.VERCEL_PROJECT_ID_EMBED }}
  VERCEL_PROJECT_ID_OG: ${{ secrets.VERCEL_PROJECT_ID_OG }}

on:
  push:
    branches: [main]
  workflow_dispatch:
    
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Deploy to Vercel ・ WEB
        env:
          PSQL_DATABASE_URL: ${{ secrets.PSQL_DATABASE_URL }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB }}
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel ・ EMBED
        env:
          PSQL_DATABASE_URL: ${{ secrets.PSQL_DATABASE_URL }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_EMBED }}
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
 
      - name: Deploy to Vercel ・ OG
        env:
          PSQL_DATABASE_URL: ${{ secrets.PSQL_DATABASE_URL }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_OG }}
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
 
